
version: 2

sources:
  - name: staging
    database: stock-project-371020
    schema: stock_data_all

    tables:
      - name: aapl_full_12_9
      - name: goog_full_12_9
      - name: msft_full_12_9
      - name: tsla_full_12_9

models:
    - name: stg_aapl_stockdata
    - name: stg_goog_stockdata
    - name: stg_msft_stockdata
    - name: stg_tsla_stockdata